export const LIST_ALL = "LIST_ALL"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const IS_SHOW_FORM = "IS_SHOW_FORM"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const IS_SHOW_POPUP_FORM = "IS_SHOW_POPUP_FORM"
export const PRODUCT_EDITTING = "PRODUCT_EDITTING"
export const PRODUCT_EDITTING_CLEAR = "PRODUCT_EDITTING_CLEAR"



